version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "90:90"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "1001:1001"

